server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  accessKeyId: AKIAQE43KATY6I6ROZNO
  secretKey: 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
  region: us-east-1
  s3:
    mock: false
    buckets:
      customer: john-fitness-app

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: johncodes
    password: codes4noor
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB